services:
  app:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./src/:/var/www/"
    networks:
      - mynetwork
    depends_on:
      - mysql

  mysql:
    image: "mysql:8.4.2"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "mysql"
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./database/data:/var/lib/mysql"
      - "./database/docker/init.sh:/docker-entrypoint-initdb.d/10-init.sh"
    networks:
      - mynetwork
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-ppassword"
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
