apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app-deployment
  labels:
    app: laravel-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app-container
        # resources:
        #          limits:
        #            cpu: 2
        #            memory: 1024
        image: 127.0.0.1:5555/laravel-app-dev:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app-service
  labels:
    app: laravel-app
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: laravel-app
  ports:
  - port: 8080
    targetPort: 8080
