name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 20
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deployment
        run: bash ./.github/scripts/pipeline.production.sh

      - name: Exit
        run: exit 0
